In [2]:
import pandas as pd

df = pd.read_csv('kc_house_data.csv')
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [3]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [4]:
y = df['price']
house_features = ['bedrooms' , 'bathrooms' , 'floors' , 'sqft_living' , 'sqft_lot', 'waterfront']
x = df[house_features]
x.describe()

,bedrooms,bathrooms,floors,sqft_living,sqft_lot,waterfront
count,21613.000000,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000
mean,3.370842,2.114757,1.494309,2079.899736,1.510697e+04,0.007542
std,0.930062,0.770163,0.539989,918.440897,4.142051e+04,0.086517
min,0.000000,0.000000,1.000000,290.000000,5.200000e+02,0.000000
25%,3.000000,1.750000,1.000000,1427.000000,5.040000e+03,0.000000
50%,3.000000,2.250000,1.500000,1910.000000,7.618000e+03,0.000000
75%,4.000000,2.500000,2.000000,2550.000000,1.068800e+04,0.000000
max,33.000000,8.000000,3.500000,13540.000000,1.651359e+06,1.000000

In [5]:
x.head()

   bedrooms  bathrooms  floors  sqft_living  sqft_lot  waterfront
0         3       1.00     1.0         1180      5650           0
1         3       2.25     2.0         2570      7242           0
2         2       1.00     1.0          770     10000           0
3         4       3.00     1.0         1960      5000           0
4         3       2.00     1.0         1680      8080           0

In [6]:
from sklearn.tree import DecisionTreeRegressor

house_model = DecisionTreeRegressor(random_state=1)

house_model.fit(x,y)

DecisionTreeRegressor(random_state=1)

In [7]:
print('Making predicitions for the following 5 houses :')
print(x.head())
print("The predicitions are :")
print(house_model.predict(x.head()))

Making predicitions for the following 5 houses :
   bedrooms  bathrooms  floors  sqft_living  sqft_lot  waterfront
0         3       1.00     1.0         1180      5650           0
1         3       2.25     2.0         2570      7242           0
2         2       1.00     1.0          770     10000           0
3         4       3.00     1.0         1960      5000           0
4         3       2.00     1.0         1680      8080           0
The predicitions are :
[221900. 538000. 180000. 604000. 510000.]

In [ ]:
## mean absolute error

from sklearn.metrics import mean_absolute_error

predicted_house_sales = house_model.predict(x)
mean_absolute_error(y, predicted_house_sales)

1802.541232899952

In [ ]:
##Overfitting and Underfitting

from sklearn.model_selection import train_test_split

train_x, val_x, train_y, val_y = train_test_split(x,y, random_state=0)

house_model = DecisionTreeRegressor()

house_model.fit(train_x,train_y)

val_predictions = house_model.predict(val_x)
print(mean_absolute_error(val_y, val_predictions))

198334.60526153469

In [11]:
def get_mae(max_leaf_nodes, train_x, val_x, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_x,train_y)
    preds_val = model.predict(val_x)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [16]:
leaves = {}
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_x, val_x, train_y, val_y)
    print("Max leaf nodes : %d \n Mean Absolute error : %d" %(max_leaf_nodes,my_mae))
    leaves[max_leaf_nodes] = my_mae

Max leaf nodes : 5
 Mean Absolute error : 176025
Max leaf nodes : 50
 Mean Absolute error : 156496
Max leaf nodes : 500
 Mean Absolute error : 159950
Max leaf nodes : 5000
 Mean Absolute error : 191467

In [19]:
print(leaves)
best_tree_size = min(leaves, key=leaves.get)

{5: 176025.62250951744, 50: 156496.5247333935, 500: 159950.05510963072, 5000: 191467.86108619987}

In [20]:
best_tree_size

50

In [21]:
final_model = DecisionTreeRegressor(max_leaf_nodes=best_tree_size, random_state=1)
final_model.fit(x,y)
print(final_model)

DecisionTreeRegressor(max_leaf_nodes=50, random_state=1)

In [24]:
final_model

DecisionTreeRegressor(max_leaf_nodes=50, random_state=1)

In [25]:
print(final_model.predict(x.head()))

[336717.38730853 555005.32395687 277444.1563981  564331.76888889
 397763.92310078]