Numpy

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
array = np.array([[2,4,6],[1,3,9]])

print(array)
print(array.size)
print(array.ndim)
print(array.shape)
print(array.dtype)
print(array.itemsize)

[[2 4 6]
 [1 3 9]]
6
2
(2, 3)
int32
4

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(np.sqrt(arr1))
print(np.sin(arr2))
print(np.log(arr2))

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1.         1.41421356 1.73205081 2.         2.23606798]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]

In [30]:
array1 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
array1[0][0]
array1[0:]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

Pandas

In [32]:
import pandas as pd
data = [1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [34]:
data2 = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data2)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [35]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

DataFrame

In [38]:
dict = {
    'Name' : ['John' , 'Chungus' , 'James'],
    'Age'  : [20,29,30], 
    'City' :['asr' , 'dlh' , 'Blr']
}

df = pd.DataFrame(dict)
print(df)
print(type(df))

      Name  Age City
0     John   20  asr
1  Chungus   29  dlh
2    James   30  Blr
<class 'pandas.DataFrame'>

In [40]:
data = [
    {'Name' : 'John' , 'Age' : 20 , 'Job' : 'Analyst'},
    {'Name' : 'Jack' , 'Age' : 31 , 'Job' : 'Web Dev'},
    {'Name' : 'Jill' , 'Age' : 21 , 'Job' : 'Ml engineer'},
] 

df = pd.DataFrame(data)
print(df)

   Name  Age          Job
0  John   20      Analyst
1  Jack   31      Web Dev
2  Jill   21  Ml engineer

In [41]:
df = pd.read_csv('vgsales.csv')
df.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [42]:
df.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [43]:
data

[{'Name': 'John', 'Age': 20, 'Job': 'Analyst'},
 {'Name': 'Jack', 'Age': 31, 'Job': 'Web Dev'},
 {'Name': 'Jill', 'Age': 21, 'Job': 'Ml engineer'}]

In [5]:
import pandas as pd
data = [
    {'Name' : 'John' , 'Age' : 20 , 'Job' : 'Analyst'},
    {'Name' : 'Jack' , 'Age' : 31 , 'Job' : 'Web Dev'},
    {'Name' : 'Jill' , 'Age' : 21 , 'Job' : 'Ml engineer'},
] 

df = pd.DataFrame(data)
print(df)

   Name  Age          Job
0  John   20      Analyst
1  Jack   31      Web Dev
2  Jill   21  Ml engineer

In [10]:
df['Salary'] = [50000,60000,70000]
df

   Name  Age          Job  Salary
0  John   20      Analyst   50000
1  Jack   31      Web Dev   60000
2  Jill   21  Ml engineer   70000

In [ ]:
df.drop('Salary',axis=1) ##temporary

   Name  Age          Job
0  John   20      Analyst
1  Jack   31      Web Dev
2  Jill   21  Ml engineer

In [13]:
df['Age'] = df['Age'] + 1

In [14]:
df

   Name  Age          Job  Salary
0  John   21      Analyst   50000
1  Jack   32      Web Dev   60000
2  Jill   22  Ml engineer   70000

In [15]:
print("Data Types :\n", df.dtypes)

print("Statistical summary: \n", df.describe())

Data Types :
 Name        str
Age       int64
Job         str
Salary    int64
dtype: object
Statistical summary:
              Age   Salary
count   3.000000      3.0
mean   25.000000  60000.0
std     6.082763  10000.0
min    21.000000  50000.0
25%    21.500000  55000.0
50%    22.000000  60000.0
75%    27.000000  65000.0
max    32.000000  70000.0

In [16]:
df = pd.read_csv('data.csv')

In [17]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [18]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [19]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [20]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [23]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [24]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [27]:
### filling missing values with the mean of the column

df['Sales_FillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_FillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [28]:
df.any()

Date            True
Category        True
Value           True
Product         True
Sales           True
Region          True
Sales_FillNA    True
dtype: bool

In [32]:
## Renaming columns

df = df.rename(columns={'Date' : 'Sale Date'})
df.head(5)

    Sale Date Category  Value   Product  Sales Region  Sales_FillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [34]:
### Changing the datatypes 
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head(5)

    Sale Date Category  Value   Product  Sales Region  Sales_FillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [35]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_FillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [3]:
##data aggregating and grouping 

import pandas as pd

df = pd.read_csv('data.csv')
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [4]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [5]:
grouped_sum = df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [ ]:
## aggregate multiple functions
grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [7]:
### merging and joining dataframes

df1 = pd.DataFrame({'Key' : ['A','B','C'] , 'Value1' : [1,2,3]})
df2 = pd.DataFrame({'Key' : ['A','B','D'] , 'Value2' : [4,5,6]})

In [9]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [10]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [11]:
## Merge Dataframe

pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [13]:
df_merged = pd.merge(df1,df2,on="Key",how="outer")
print(df_merged)

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [22]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [28]:
## Data Reading
import pandas as pd
from io import StringIO

Data = '{"employee_name" : "James" , "email" : "james@gmail.com" , "job_profile": [{"title1" : "Team Lead", "title2" : "Software Developer"}]}'
df = pd.read_json(StringIO(Data))

In [29]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Software De..."

In [30]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Software Developer"}}}'

In [31]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Software Developer"}}}'

In [32]:
df.to_csv("simple.csv")

In [36]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)

In [38]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [39]:
df = pd.read_excel('Project-Management-Sample-Data.xlsx')

In [41]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
10,NaN,Product Dev,Quality Assurance,Fiona,2024-01-20 00:00:00,10,2024-01-30 00:00:00,0.78
11,NaN,Product Dev,User Interface Design,Gabriel,2024-02-04 00:00:00,25,2024-02-29 00:00:00,0
12,NaN,Customer Svc,Service Improvement,Hannah,2024-02-01 00:00:00,22,2024-02-23 00:00:00,1
13,NaN,Customer Svc,Ticket Resolution,Ian,2024-02-24 00:00:00,25,2024-03-20 00:00:00,1
14,NaN,Customer Svc,Customer Feedback,Julia,2024-03-21 00:00:00,30,2024-04-20 00:00:00,0
15,NaN,Financial,Budget Analysis,Kevin,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0.1
16,NaN,Financial,Financial Reporting,Mark,2024-02-13 00:00:00,21,2024-02-09 00:00:00,0.78
17,NaN,Financial,Investment Planning,Mark,2024-03-19 00:00:00,25,2024-04-13 00:00:00,1
18,NaN,Research,Market Trends Analysis,Nathan,2024-01-02 00:00:00,23,2024-01-25 00:00:00,0.5
19,NaN,Research,Data Collection,Olivia,2024-01-26 00:00:00,32,2024-02-27 00:00:00,0
20,NaN,Research,Research Paper Writing,Peter,2024-02-28 00:00:00,27,2024-03-26 00:00:00,0
21,NaN,Development,Software Development,Quinn,2024-01-02 00:00:00,36,2024-02-07 00:00:00,1
22,NaN,Development,Feature Enhancement,Rachel,2024-02-08 00:00:00,34,2024-03-13 00:00:00,0
23,NaN,Development,Code Review,Sam,2024-03-14 00:00:00,30,2024-04-13 00:00:00,0
24,NaN,Production,Manufacturing,Tim,2024-01-03 00:00:00,47,2024-02-19 00:00:00,0.3
25,NaN,Production,Quality Control,Ursula,2024-02-17 00:00:00,27,2024-03-15 00:00:00,0
26,NaN,Production,Packaging Design,Victor,2024-03-14 00:00:00,22,2024-04-05 00:00:00,0
27,NaN,Sales,Lead Generation,Wendy,2024-01-03 00:00:00,60,2024-03-03 00:00:00,0.7
28,NaN,Sales,Client Meetings,Xavier,2024-01-06 00:00:00,20,2024-01-26 00:00:00,0.78
29,NaN,Sales,Contract Negotiation,Yvette,2024-02-03 00:00:00,35,2024-03-09 00:00:00,0
30,NaN,Support,Technical Support,Zoe,2024-01-01 00:00:00,25,2024-01-26 00:00:00,1
31,NaN,Support,Bug Fixes,Aaron,2024-01-27 00:00:00,31,2024-02-27 00:00:00,1
32,NaN,Support,Software Updates,Bella,2024-03-02 00:00:00,22,2024-03-24 00:00:00,0
33,NaN,Operations,Process Optimization,Calvin,2024-01-03 00:00:00,30,2024-02-02 00:00:00,0.4
34,NaN,Operations,Inventory Management,Diane,2024-02-03 00:00:00,25,2024-02-28 00:00:00,0
35,NaN,Operations,Facility Maintenance,Edward,2024-02-29 00:00:00,20,2024-03-20 00:00:00,0
36,NaN,Consulting,Strategic Planning,Fiona,2024-01-02 00:00:00,35,2024-02-06 00:00:00,0.6
37,NaN,Consulting,Market Expansion,Gary,2024-02-02 00:00:00,32,2024-03-05 00:00:00,0
38,NaN,Consulting,Client Advisory,Helen,2024-03-06 00:00:00,25,2024-03-31 00:00:00,0
39,NaN,Training,Employee Training,Isaac,2024-01-04 00:00:00,27,2024-01-31 00:00:00,0.8
40,NaN,Training,Certification Programs,Jane,2024-01-28 00:00:00,30,2024-02-27 00:00:00,0
41,NaN,Training,Skill Development,Kyle,2024-02-28 00:00:00,22,2024-03-21 00:00:00,0
42,NaN,Events,Event Planning,Laura,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.3
43,NaN,Events,Conference Management,Mike,2024-02-03 00:00:00,20,2024-02-23 00:00:00,0
44,NaN,Events,Sponsorship Coordinatio,n Nancy,2024-02-24 00:00:00,35,2024-03-30 00:00:00,0
45,NaN,Logistics,Supply Chain Management,Oscar,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.5
46,NaN,Logistics,Transportation Planning,Patricia,2024-01-29 00:00:00,30,2024-02-28 00:00:00,1
47,NaN,Logistics,Inventory Optimization,Quentin,2024-03-29 00:00:00,20,2024-04-18 00:00:00,0
48,NaN,Engineering,Product Design,Rachel,2024-01-02 00:00:00,25,2024-01-27 00:00:00,0.2
49,NaN,Engineering,System Integration,Sam,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0
50,NaN,Engineering,Prototype Testing,Tom,2024-02-23 00:00:00,27,2024-03-21 00:00:00,0

In [42]:
df.to_pickle('df_excel')

In [43]:
pd.read_pickle('df_excel')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
10,NaN,Product Dev,Quality Assurance,Fiona,2024-01-20 00:00:00,10,2024-01-30 00:00:00,0.78
11,NaN,Product Dev,User Interface Design,Gabriel,2024-02-04 00:00:00,25,2024-02-29 00:00:00,0
12,NaN,Customer Svc,Service Improvement,Hannah,2024-02-01 00:00:00,22,2024-02-23 00:00:00,1
13,NaN,Customer Svc,Ticket Resolution,Ian,2024-02-24 00:00:00,25,2024-03-20 00:00:00,1
14,NaN,Customer Svc,Customer Feedback,Julia,2024-03-21 00:00:00,30,2024-04-20 00:00:00,0
15,NaN,Financial,Budget Analysis,Kevin,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0.1
16,NaN,Financial,Financial Reporting,Mark,2024-02-13 00:00:00,21,2024-02-09 00:00:00,0.78
17,NaN,Financial,Investment Planning,Mark,2024-03-19 00:00:00,25,2024-04-13 00:00:00,1
18,NaN,Research,Market Trends Analysis,Nathan,2024-01-02 00:00:00,23,2024-01-25 00:00:00,0.5
19,NaN,Research,Data Collection,Olivia,2024-01-26 00:00:00,32,2024-02-27 00:00:00,0
20,NaN,Research,Research Paper Writing,Peter,2024-02-28 00:00:00,27,2024-03-26 00:00:00,0
21,NaN,Development,Software Development,Quinn,2024-01-02 00:00:00,36,2024-02-07 00:00:00,1
22,NaN,Development,Feature Enhancement,Rachel,2024-02-08 00:00:00,34,2024-03-13 00:00:00,0
23,NaN,Development,Code Review,Sam,2024-03-14 00:00:00,30,2024-04-13 00:00:00,0
24,NaN,Production,Manufacturing,Tim,2024-01-03 00:00:00,47,2024-02-19 00:00:00,0.3
25,NaN,Production,Quality Control,Ursula,2024-02-17 00:00:00,27,2024-03-15 00:00:00,0
26,NaN,Production,Packaging Design,Victor,2024-03-14 00:00:00,22,2024-04-05 00:00:00,0
27,NaN,Sales,Lead Generation,Wendy,2024-01-03 00:00:00,60,2024-03-03 00:00:00,0.7
28,NaN,Sales,Client Meetings,Xavier,2024-01-06 00:00:00,20,2024-01-26 00:00:00,0.78
29,NaN,Sales,Contract Negotiation,Yvette,2024-02-03 00:00:00,35,2024-03-09 00:00:00,0
30,NaN,Support,Technical Support,Zoe,2024-01-01 00:00:00,25,2024-01-26 00:00:00,1
31,NaN,Support,Bug Fixes,Aaron,2024-01-27 00:00:00,31,2024-02-27 00:00:00,1
32,NaN,Support,Software Updates,Bella,2024-03-02 00:00:00,22,2024-03-24 00:00:00,0
33,NaN,Operations,Process Optimization,Calvin,2024-01-03 00:00:00,30,2024-02-02 00:00:00,0.4
34,NaN,Operations,Inventory Management,Diane,2024-02-03 00:00:00,25,2024-02-28 00:00:00,0
35,NaN,Operations,Facility Maintenance,Edward,2024-02-29 00:00:00,20,2024-03-20 00:00:00,0
36,NaN,Consulting,Strategic Planning,Fiona,2024-01-02 00:00:00,35,2024-02-06 00:00:00,0.6
37,NaN,Consulting,Market Expansion,Gary,2024-02-02 00:00:00,32,2024-03-05 00:00:00,0
38,NaN,Consulting,Client Advisory,Helen,2024-03-06 00:00:00,25,2024-03-31 00:00:00,0
39,NaN,Training,Employee Training,Isaac,2024-01-04 00:00:00,27,2024-01-31 00:00:00,0.8
40,NaN,Training,Certification Programs,Jane,2024-01-28 00:00:00,30,2024-02-27 00:00:00,0
41,NaN,Training,Skill Development,Kyle,2024-02-28 00:00:00,22,2024-03-21 00:00:00,0
42,NaN,Events,Event Planning,Laura,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.3
43,NaN,Events,Conference Management,Mike,2024-02-03 00:00:00,20,2024-02-23 00:00:00,0
44,NaN,Events,Sponsorship Coordinatio,n Nancy,2024-02-24 00:00:00,35,2024-03-30 00:00:00,0
45,NaN,Logistics,Supply Chain Management,Oscar,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.5
46,NaN,Logistics,Transportation Planning,Patricia,2024-01-29 00:00:00,30,2024-02-28 00:00:00,1
47,NaN,Logistics,Inventory Optimization,Quentin,2024-03-29 00:00:00,20,2024-04-18 00:00:00,0
48,NaN,Engineering,Product Design,Rachel,2024-01-02 00:00:00,25,2024-01-27 00:00:00,0.2
49,NaN,Engineering,System Integration,Sam,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0
50,NaN,Engineering,Prototype Testing,Tom,2024-02-23 00:00:00,27,2024-03-21 00:00:00,0